// tests/test_fa2_full.cpp
//
// Tests for the FA2Tiler (C++ instruction generator) and for the
// schedules/fa2_full_matrix.yaml generated by scripts/gen_fa2_schedule.py.
//
// Coverage:
//   1.  WorkloadAttention YAML parse
//   2.  Nq / Nkv ceiling division
//   3.  Instruction count formula  (5 + Nkv*15 + 4 per Q-tile)
//   4.  Q0 prologue ids / ops / deps
//   5.  Q0/KV0 inner-tile ops and deps
//   6.  Double-buffer ping-pong (K_buf0 / K_buf1 alternation)
//   7.  Cross-KV DMA prev_dma chain (load_K[j] depends on load_V[j-1])
//   8.  update_rowmax serial chain
//   9.  update_rowsum serial chain
//  10.  scale_O depends on prev_accumulate
//  11.  Q0 epilogue (normalize / logsumexp / store_O / store_L)
//  12.  Q1 prologue depends on store_L[Q0]
//  13.  seed_hbm creates all expected HBM TensorStore keys
//  14.  FA2 full-matrix YAML: metadata fields correct
//  15.  FA2 full-matrix YAML: instruction count == 15648
//  16.  FA2Tiler small (2×2): all instructions complete (delay-unit sim)
//  17.  FA2Tiler small (2×2): DMA kv=1 starts before GEMM kv=0 ends
//  18.  FA2Tiler small (2×2): Q-tile store_L[Q0] starts before Q1 prologue
//  19.  FA2Tiler full (32×32): all 15648 instructions complete (delay-unit sim)
//  20.  FA2 full-matrix YAML: all 15648 instructions complete (delay-unit sim)

#include <doctest/doctest.h>

#include <unordered_map>
#include <string>
#include <algorithm>
#include <sstream>
#include <stdexcept>

#include "core/event_engine.h"
#include "core/tensor_store.h"
#include "config/arch_config.h"
#include "schedule/schedule.h"
#include "schedule/op_registry.h"
#include "schedule/scheduler.h"
#include "schedule/fa2_tiler.h"
#include "units/delay_unit.h"

using namespace sim;

// SIM_PROJECT_ROOT is injected by CMake (see tests/CMakeLists.txt).
static const std::string FA2_ATT_WL   = std::string(SIM_PROJECT_ROOT) + "/workloads/fa2_attention.yaml";
static const std::string FA2_FULL_SCH = std::string(SIM_PROJECT_ROOT) + "/schedules/fa2_full_matrix.yaml";
static const std::string ARCH_PATH    = std::string(SIM_PROJECT_ROOT) + "/configs/default.yaml";

// ---------------------------------------------------------------------------
// Workload dimensions for the "small" test case  (Nq=2, Nkv=2)
// ---------------------------------------------------------------------------
static constexpr int NQ_SMALL  = 2;
static constexpr int NKV_SMALL = 2;
static constexpr int BR_SMALL  = 128;
static constexpr int BC_SMALL  = 128;
static constexpr int DH_SMALL  = 128;

// Per-Q-tile instruction count formula:  5 prologue + Nkv*15 inner + 4 epilogue
static constexpr int INSTRS_PER_Q_SMALL = 5 + NKV_SMALL * 15 + 4;  // 39
static constexpr int INSTRS_SMALL       = NQ_SMALL * INSTRS_PER_Q_SMALL;  // 78

// Full LLaMA-3-8B single-head workload
static constexpr int NQ_FULL            = 32;
static constexpr int NKV_FULL           = 32;
static constexpr int INSTRS_PER_Q_FULL  = 5 + NKV_FULL * 15 + 4;   // 489
static constexpr int INSTRS_FULL        = NQ_FULL * INSTRS_PER_Q_FULL;  // 15648

// ---------------------------------------------------------------------------
// Instruction-ID offsets within Q0 for the small (Nkv=2) workload.
//
// Q0 prologue  (0–4):
//   0 = init_O   1 = init_m   2 = init_l   3 = load_Q   4 = stage_Q
//
// Q0/KV0 inner tile (5–19):
//   5=load_K  6=load_V  7=transpose  8=wl_K  9=gemm_S
//   10=scale_S  11=rowmax  12=update_rowmax  13=exp_shift
//   14=update_rowsum  15=scale_O  16=stage_P  17=wl_V  18=gemm_T  19=accumulate
//
// Q0/KV1 inner tile (20–34) — same offsets + 15
//
// Q0 epilogue (35–38):
//   35=normalize  36=logsumexp  37=store_O  38=store_L
//
// Q1 prologue starts at id 39  (= INSTRS_PER_Q_SMALL)
// ---------------------------------------------------------------------------
static constexpr int OFF_LOAD_K         = 0;   // relative offset inside a KV tile
static constexpr int OFF_LOAD_V         = 1;
static constexpr int OFF_TRANSPOSE      = 2;
static constexpr int OFF_WL_K           = 3;
static constexpr int OFF_GEMM_S         = 4;
static constexpr int OFF_SCALE_S        = 5;
static constexpr int OFF_ROWMAX         = 6;
static constexpr int OFF_UPDATE_ROWMAX  = 7;
static constexpr int OFF_EXP_SHIFT      = 8;
static constexpr int OFF_UPDATE_ROWSUM  = 9;
static constexpr int OFF_SCALE_O        = 10;
static constexpr int OFF_STAGE_P        = 11;
static constexpr int OFF_WL_V           = 12;
static constexpr int OFF_GEMM_T         = 13;
static constexpr int OFF_ACCUMULATE     = 14;

// Helper: id of instruction at (qi=0, kv, off)
static constexpr int id_kv(int kv, int off) {
    return 5 + kv * 15 + off;
}

// ---------------------------------------------------------------------------
// Test helpers
// ---------------------------------------------------------------------------
namespace {

bool has_dep(const Instruction& inst, InstructionId dep) {
    return std::find(inst.depends_on.begin(), inst.depends_on.end(), dep)
           != inst.depends_on.end();
}

// Register every FA2 op as a simple fixed-latency delay op.
void add_all_delay_ops(OpRegistry& reg) {
    auto handler = [](const IssueCtx& ctx) {
        auto targets = ctx.engine.find_unit_pool(ctx.inst.unit);
        REQUIRE(!targets.empty());
        Cycle lat = static_cast<Cycle>(pget_int(ctx.inst.params, "latency_cycles", 10));
        UnitReservation res = ctx.scheduler.reserve_unit_pool(targets, lat);
        Event e;
        e.type    = EventType::OP_START;
        e.target  = res.id;
        e.cycle   = res.start;
        e.instr   = ctx.inst.id;
        e.label   = ctx.inst.label;
        e.payload = static_cast<int64_t>(lat);
        ctx.engine.schedule(std::move(e));
    };
    for (const char* op : {"gemm", "weight_load", "dma_load", "dma_store", "dma_stage",
                            "init_fill", "transpose",
                            "scale", "rowmax", "update_rowmax", "exp_shift",
                            "update_rowsum", "accumulate", "normalize", "logsumexp",
                            "sram_read", "sram_write", "delay"})
        reg.register_op(op, handler);
}

// Register one DelayUnit per FA2 hardware resource.
void register_fa2_units(EventEngine& engine, std::ostream& ss) {
    for (const char* n : {"systolic", "access_core_0",
                          "vector_core_0", "vector_core_1", "vector_core_2",
                          "dma_0"})
        engine.register_unit(std::make_unique<DelayUnit>(n, 0, nullptr, ss));
}

void wire(EventEngine& engine, Scheduler& sched) {
    for (UnitId uid = 0; uid < static_cast<UnitId>(engine.num_units()); uid++)
        if (auto* du = dynamic_cast<DelayUnit*>(engine.get_unit(uid)))
            du->set_scheduler(&sched);
}

// Build the small (Nq=2, Nkv=2) instruction set.
std::vector<Instruction> build_small(TensorStore& ts) {
    WorkloadAttention wl;
    wl.seq_len = static_cast<uint32_t>(NQ_SMALL * BR_SMALL);  // 256
    wl.Br      = BR_SMALL;
    wl.Bc      = BC_SMALL;
    wl.d_head  = DH_SMALL;
    ArchConfig arch = ArchConfig::from_yaml_file(ARCH_PATH);
    return FA2Tiler::decompose(wl, arch, ts);
}

}  // namespace

// ===========================================================================
// 1. WorkloadAttention YAML parsing
// ===========================================================================

TEST_CASE("FA2Tiler: WorkloadAttention fields parsed from YAML") {
    WorkloadAttention wl = FA2Tiler::from_yaml_file(FA2_ATT_WL);
    CHECK(wl.seq_len == 4096);
    CHECK(wl.d_head  == 128);
    CHECK(wl.Br      == 128);
    CHECK(wl.Bc      == 128);
    CHECK(wl.fill    == "random");
    CHECK(wl.Nq()    == 32);
    CHECK(wl.Nkv()   == 32);
}

// ===========================================================================
// 2. Nq / Nkv ceiling division
// ===========================================================================

TEST_CASE("FA2Tiler: Nq/Nkv ceiling division is correct") {
    WorkloadAttention wl;

    wl.seq_len = 256; wl.Br = 128; wl.Bc = 128;
    CHECK(wl.Nq()  == 2);
    CHECK(wl.Nkv() == 2);

    // Non-multiple: ceil(300 / 128) = 3
    wl.seq_len = 300;
    CHECK(wl.Nq()  == 3);
    CHECK(wl.Nkv() == 3);

    // Exact power-of-2
    wl.seq_len = 4096; wl.Br = 128;
    CHECK(wl.Nq() == 32);
}

// ===========================================================================
// 3. Instruction count formula
// ===========================================================================

TEST_CASE("FA2Tiler: instruction count formula — 5 + 15*Nkv + 4 per Q-tile") {
    ArchConfig arch = ArchConfig::from_yaml_file(ARCH_PATH);

    // 1×1 → 5 + 15 + 4 = 24
    {
        TensorStore ts;
        WorkloadAttention wl; wl.seq_len=128; wl.Br=128; wl.Bc=128; wl.d_head=128;
        auto v = FA2Tiler::decompose(wl, arch, ts);
        CHECK(v.size() == 24u);
    }
    // 2×2 → 2 * (5 + 30 + 4) = 78
    {
        TensorStore ts;
        auto v = build_small(ts);
        CHECK(v.size() == static_cast<size_t>(INSTRS_SMALL));
    }
    // 1×4 → 5 + 60 + 4 = 69
    {
        TensorStore ts;
        WorkloadAttention wl; wl.seq_len=128; wl.Br=128; wl.Bc=128; wl.d_head=128;
        // simulate 4 KV tiles by making Bc small and seq_len = 4*Bc
        // Actually easier: just set seq_len=128, Bc=32 so Nkv=4
        wl.Bc = 32; wl.seq_len = 128;
        auto v = FA2Tiler::decompose(wl, arch, ts);
        int expected = 5 + 4*15 + 4;
        CHECK(v.size() == static_cast<size_t>(expected));
    }
}

// ===========================================================================
// 4. Q0 prologue: ids, ops, units, deps
// ===========================================================================

TEST_CASE("FA2Tiler: Q0 prologue ids, ops, units, no deps") {
    TensorStore ts;
    auto v = build_small(ts);

    // id=0: init_fill O_acc (access_core, no deps)
    CHECK(v[0].id   == 0);
    CHECK(v[0].op   == "init_fill");
    CHECK(v[0].unit == "access_core");
    CHECK(v[0].depends_on.empty());
    CHECK(pget_str(v[0].params, "destination").find("O_acc") != std::string::npos);

    // id=1: init_fill m (access_core, no deps, -inf)
    CHECK(v[1].id   == 1);
    CHECK(v[1].op   == "init_fill");
    CHECK(v[1].depends_on.empty());
    CHECK(pget_str(v[1].params, "destination").find(".m") != std::string::npos);

    // id=2: init_fill l (access_core, no deps, 0)
    CHECK(v[2].id   == 2);
    CHECK(v[2].op   == "init_fill");
    CHECK(v[2].depends_on.empty());
    CHECK(pget_str(v[2].params, "destination").find(".l") != std::string::npos);

    // id=3: dma_load Q (dma, no deps)
    CHECK(v[3].id   == 3);
    CHECK(v[3].op   == "dma_load");
    CHECK(v[3].unit == "dma");
    CHECK(v[3].depends_on.empty());
    // Source must reference HBM.Q starting at row 0
    std::string src = pget_str(v[3].params, "source");
    CHECK(src.find("HBM.Q[0:") != std::string::npos);

    // id=4: dma_stage Q → operand (dma, depends only on load_Q=3)
    CHECK(v[4].id   == 4);
    CHECK(v[4].op   == "dma_stage");
    CHECK(v[4].unit == "dma");
    CHECK(v[4].depends_on.size() == 1);
    CHECK(has_dep(v[4], 3));
    CHECK(pget_str(v[4].params, "destination").find("Q_operand") != std::string::npos);
}

// ===========================================================================
// 5. Q0/KV0 inner-tile structure
// ===========================================================================

TEST_CASE("FA2Tiler: Q0/KV0 inner-tile ops, units, deps") {
    TensorStore ts;
    auto v = build_small(ts);

    // --- DMA load K and V ---
    CHECK(v[id_kv(0,OFF_LOAD_K)].op == "dma_load");
    CHECK(v[id_kv(0,OFF_LOAD_K)].unit == "dma");
    // load_K[kv=0] depends on stage_Q (id=4)
    REQUIRE(has_dep(v[id_kv(0,OFF_LOAD_K)], 4));

    CHECK(v[id_kv(0,OFF_LOAD_V)].op == "dma_load");
    // load_V depends on load_K only
    REQUIRE(has_dep(v[id_kv(0,OFF_LOAD_V)], id_kv(0,OFF_LOAD_K)));

    // --- Transpose ---
    CHECK(v[id_kv(0,OFF_TRANSPOSE)].op == "transpose");
    CHECK(v[id_kv(0,OFF_TRANSPOSE)].unit == "access_core");
    // transpose depends on load_K (not load_V — can run in parallel with load_V)
    REQUIRE(has_dep(v[id_kv(0,OFF_TRANSPOSE)], id_kv(0,OFF_LOAD_K)));
    // transpose must NOT depend on load_V
    CHECK(!has_dep(v[id_kv(0,OFF_TRANSPOSE)], id_kv(0,OFF_LOAD_V)));

    // --- Weight-load K ---
    CHECK(v[id_kv(0,OFF_WL_K)].op == "weight_load");
    CHECK(v[id_kv(0,OFF_WL_K)].unit == "systolic");
    REQUIRE(has_dep(v[id_kv(0,OFF_WL_K)], id_kv(0,OFF_TRANSPOSE)));

    // --- GEMM S = Q × K^T ---
    CHECK(v[id_kv(0,OFF_GEMM_S)].op == "gemm");
    CHECK(v[id_kv(0,OFF_GEMM_S)].unit == "systolic");
    REQUIRE(has_dep(v[id_kv(0,OFF_GEMM_S)], 4));                       // stage_Q
    REQUIRE(has_dep(v[id_kv(0,OFF_GEMM_S)], id_kv(0,OFF_WL_K)));
    CHECK(pget_str(v[id_kv(0,OFF_GEMM_S)].params,"source_a").find("Q_operand") != std::string::npos);
    CHECK(pget_str(v[id_kv(0,OFF_GEMM_S)].params,"destination").find("S_tile") != std::string::npos);

    // --- Scale S, rowmax ---
    CHECK(v[id_kv(0,OFF_SCALE_S)].op == "scale");
    REQUIRE(has_dep(v[id_kv(0,OFF_SCALE_S)], id_kv(0,OFF_GEMM_S)));

    CHECK(v[id_kv(0,OFF_ROWMAX)].op == "rowmax");
    REQUIRE(has_dep(v[id_kv(0,OFF_ROWMAX)], id_kv(0,OFF_SCALE_S)));

    // --- update_rowmax: needs rowmax(kv=0) AND init_m (id=1) ---
    CHECK(v[id_kv(0,OFF_UPDATE_ROWMAX)].op == "update_rowmax");
    REQUIRE(has_dep(v[id_kv(0,OFF_UPDATE_ROWMAX)], id_kv(0,OFF_ROWMAX)));
    REQUIRE(has_dep(v[id_kv(0,OFF_UPDATE_ROWMAX)], 1));   // prev_update_rowmax = init_m

    // --- exp_shift ---
    CHECK(v[id_kv(0,OFF_EXP_SHIFT)].op == "exp_shift");
    REQUIRE(has_dep(v[id_kv(0,OFF_EXP_SHIFT)], id_kv(0,OFF_UPDATE_ROWMAX)));

    // --- update_rowsum: needs exp_shift, update_rowmax, init_l (id=2) ---
    CHECK(v[id_kv(0,OFF_UPDATE_ROWSUM)].op == "update_rowsum");
    REQUIRE(has_dep(v[id_kv(0,OFF_UPDATE_ROWSUM)], id_kv(0,OFF_EXP_SHIFT)));
    REQUIRE(has_dep(v[id_kv(0,OFF_UPDATE_ROWSUM)], id_kv(0,OFF_UPDATE_ROWMAX)));
    REQUIRE(has_dep(v[id_kv(0,OFF_UPDATE_ROWSUM)], 2));   // prev_update_rowsum = init_l

    // --- scale_O: runs on 2nd vector core (parallel with exp_shift)
    //   depends on update_rowmax AND prev_accumulate=init_O (id=0) ---
    CHECK(v[id_kv(0,OFF_SCALE_O)].op == "scale");
    REQUIRE(has_dep(v[id_kv(0,OFF_SCALE_O)], id_kv(0,OFF_UPDATE_ROWMAX)));
    REQUIRE(has_dep(v[id_kv(0,OFF_SCALE_O)], 0));         // prev_accumulate = init_O

    // --- stage_P: waits for exp_shift (data) AND load_V (DMA ordered) ---
    CHECK(v[id_kv(0,OFF_STAGE_P)].op == "dma_stage");
    REQUIRE(has_dep(v[id_kv(0,OFF_STAGE_P)], id_kv(0,OFF_EXP_SHIFT)));
    REQUIRE(has_dep(v[id_kv(0,OFF_STAGE_P)], id_kv(0,OFF_LOAD_V)));
    CHECK(pget_str(v[id_kv(0,OFF_STAGE_P)].params,"destination").find("P_operand") != std::string::npos);

    // --- Weight-load V: after GEMM S and after load_V (structural + data) ---
    CHECK(v[id_kv(0,OFF_WL_V)].op == "weight_load");
    REQUIRE(has_dep(v[id_kv(0,OFF_WL_V)], id_kv(0,OFF_GEMM_S)));
    REQUIRE(has_dep(v[id_kv(0,OFF_WL_V)], id_kv(0,OFF_LOAD_V)));

    // --- GEMM T = P × V ---
    CHECK(v[id_kv(0,OFF_GEMM_T)].op == "gemm");
    REQUIRE(has_dep(v[id_kv(0,OFF_GEMM_T)], id_kv(0,OFF_STAGE_P)));
    REQUIRE(has_dep(v[id_kv(0,OFF_GEMM_T)], id_kv(0,OFF_WL_V)));

    // --- Accumulate: needs scale_O (free O_acc) and gemm_T (result) ---
    CHECK(v[id_kv(0,OFF_ACCUMULATE)].op == "accumulate");
    REQUIRE(has_dep(v[id_kv(0,OFF_ACCUMULATE)], id_kv(0,OFF_SCALE_O)));
    REQUIRE(has_dep(v[id_kv(0,OFF_ACCUMULATE)], id_kv(0,OFF_GEMM_T)));
}

// ===========================================================================
// 6. Double-buffer ping-pong
// ===========================================================================

TEST_CASE("FA2Tiler: double-buffer K_buf0/K_buf1 alternation") {
    TensorStore ts;
    auto v = build_small(ts);

    // kv=0 → K_buf0, V_buf0
    CHECK(pget_str(v[id_kv(0,OFF_LOAD_K)].params,"destination") == "shared_ibuf.K_buf0");
    CHECK(pget_str(v[id_kv(0,OFF_LOAD_V)].params,"destination") == "shared_ibuf.V_buf0");

    // kv=1 → K_buf1, V_buf1
    CHECK(pget_str(v[id_kv(1,OFF_LOAD_K)].params,"destination") == "shared_ibuf.K_buf1");
    CHECK(pget_str(v[id_kv(1,OFF_LOAD_V)].params,"destination") == "shared_ibuf.V_buf1");

    // Transpose sources match corresponding K buffers
    CHECK(pget_str(v[id_kv(0,OFF_TRANSPOSE)].params,"source") == "shared_ibuf.K_buf0");
    CHECK(pget_str(v[id_kv(1,OFF_TRANSPOSE)].params,"source") == "shared_ibuf.K_buf1");

    // wl_V source matches corresponding V buffer
    CHECK(pget_str(v[id_kv(0,OFF_WL_V)].params,"source") == "shared_ibuf.V_buf0");
    CHECK(pget_str(v[id_kv(1,OFF_WL_V)].params,"source") == "shared_ibuf.V_buf1");
}

// ===========================================================================
// 7. Cross-KV DMA chain: load_K[j] depends on load_V[j-1]
// ===========================================================================

TEST_CASE("FA2Tiler: load_K[kv] depends on load_V[kv-1] (prev_dma)") {
    TensorStore ts;
    auto v = build_small(ts);

    // load_K[kv=1] must depend on load_V[kv=0]
    REQUIRE(has_dep(v[id_kv(1,OFF_LOAD_K)], id_kv(0,OFF_LOAD_V)));

    // load_K[kv=0] depends on stage_Q (not on load_V of a previous tile)
    CHECK(!has_dep(v[id_kv(0,OFF_LOAD_K)], id_kv(0,OFF_LOAD_V)));
}

// ===========================================================================
// 8. update_rowmax serial chain
// ===========================================================================

TEST_CASE("FA2Tiler: update_rowmax[kv] depends on update_rowmax[kv-1]") {
    TensorStore ts;
    auto v = build_small(ts);

    // update_rowmax[kv=1] must depend on update_rowmax[kv=0]
    REQUIRE(has_dep(v[id_kv(1,OFF_UPDATE_ROWMAX)], id_kv(0,OFF_UPDATE_ROWMAX)));
}

// ===========================================================================
// 9. update_rowsum serial chain
// ===========================================================================

TEST_CASE("FA2Tiler: update_rowsum[kv] depends on update_rowsum[kv-1]") {
    TensorStore ts;
    auto v = build_small(ts);

    // update_rowsum[kv=1] must depend on update_rowsum[kv=0]
    REQUIRE(has_dep(v[id_kv(1,OFF_UPDATE_ROWSUM)], id_kv(0,OFF_UPDATE_ROWSUM)));
}

// ===========================================================================
// 10. scale_O depends on prev_accumulate
// ===========================================================================

TEST_CASE("FA2Tiler: scale_O[kv] depends on accumulate[kv-1]") {
    TensorStore ts;
    auto v = build_small(ts);

    // scale_O[kv=1] must depend on accumulate[kv=0]
    REQUIRE(has_dep(v[id_kv(1,OFF_SCALE_O)], id_kv(0,OFF_ACCUMULATE)));
}

// ===========================================================================
// 11. Q0 epilogue structure
// ===========================================================================

TEST_CASE("FA2Tiler: Q0 epilogue — normalize/logsumexp/store_O/store_L deps") {
    TensorStore ts;
    auto v = build_small(ts);

    // Epilogue starts after all inner-tile instructions.
    // normalize = 5 + NKV_SMALL*15 = 5 + 30 = 35
    static constexpr int ID_NORM   = 5 + NKV_SMALL * 15;       // 35
    static constexpr int ID_LSUM   = ID_NORM + 1;               // 36
    static constexpr int ID_STOR_O = ID_NORM + 2;               // 37
    static constexpr int ID_STOR_L = ID_NORM + 3;               // 38

    // Last inner-tile ids
    static constexpr int LAST_ACC     = id_kv(NKV_SMALL-1, OFF_ACCUMULATE);    // 34
    static constexpr int LAST_ROWSUM  = id_kv(NKV_SMALL-1, OFF_UPDATE_ROWSUM); // 29
    static constexpr int LAST_ROWMAX  = id_kv(NKV_SMALL-1, OFF_UPDATE_ROWMAX); // 27
    static constexpr int LAST_LOAD_V  = id_kv(NKV_SMALL-1, OFF_LOAD_V);        // 21

    // normalize: waits for last accumulate and last update_rowsum
    CHECK(v[ID_NORM].op == "normalize");
    REQUIRE(has_dep(v[ID_NORM], LAST_ACC));
    REQUIRE(has_dep(v[ID_NORM], LAST_ROWSUM));

    // logsumexp: waits for last update_rowmax, last update_rowsum, and normalize
    CHECK(v[ID_LSUM].op == "logsumexp");
    REQUIRE(has_dep(v[ID_LSUM], LAST_ROWMAX));
    REQUIRE(has_dep(v[ID_LSUM], LAST_ROWSUM));
    REQUIRE(has_dep(v[ID_LSUM], ID_NORM));

    // store_O: waits for normalize (data) and last load_V (DMA serialization)
    CHECK(v[ID_STOR_O].op == "dma_store");
    REQUIRE(has_dep(v[ID_STOR_O], ID_NORM));
    REQUIRE(has_dep(v[ID_STOR_O], LAST_LOAD_V));
    CHECK(pget_str(v[ID_STOR_O].params,"destination").find("HBM.O[0:") != std::string::npos);

    // store_L: waits for logsumexp (data) and store_O (DMA serialization)
    CHECK(v[ID_STOR_L].op == "dma_store");
    REQUIRE(has_dep(v[ID_STOR_L], ID_LSUM));
    REQUIRE(has_dep(v[ID_STOR_L], ID_STOR_O));
    CHECK(pget_str(v[ID_STOR_L].params,"destination").find("HBM.L[0:") != std::string::npos);
}

// ===========================================================================
// 12. Q1 prologue depends on store_L[Q0]
// ===========================================================================

TEST_CASE("FA2Tiler: Q1 prologue depends on store_L[Q0]") {
    TensorStore ts;
    auto v = build_small(ts);

    // store_L for Q0 is the last instruction of Q0 (id = INSTRS_PER_Q_SMALL - 1)
    static constexpr int STOR_L_Q0 = INSTRS_PER_Q_SMALL - 1;  // 38
    static constexpr int Q1_START  = INSTRS_PER_Q_SMALL;       // 39

    REQUIRE(v[STOR_L_Q0].op == "dma_store");

    // The four Q1 prologue ops (init_O, init_m, init_l, load_Q) must all
    // depend on store_L[Q0] — this enforces sequential Q-tile processing.
    for (int i = 0; i < 4; i++) {
        INFO("Q1 prologue id=" << (Q1_START + i) << " must depend on store_L[Q0]=" << STOR_L_Q0);
        REQUIRE(has_dep(v[Q1_START + i], static_cast<InstructionId>(STOR_L_Q0)));
    }

    // stage_Q of Q1 depends only on load_Q of Q1 (not on store_L)
    CHECK(v[Q1_START + 4].op == "dma_stage");
    REQUIRE(has_dep(v[Q1_START + 4], static_cast<InstructionId>(Q1_START + 3)));
    CHECK(!has_dep(v[Q1_START + 4], static_cast<InstructionId>(STOR_L_Q0)));

    // Q1 load_K for kv=0 (id = Q1_START + 5 = 44) depends on Q1 stage_Q (id=43)
    REQUIRE(has_dep(v[Q1_START + 5], static_cast<InstructionId>(Q1_START + 4)));
}

// ===========================================================================
// 13. seed_hbm creates all expected HBM TensorStore keys
// ===========================================================================

TEST_CASE("FA2Tiler: seed_hbm creates all expected HBM keys") {
    TensorStore ts;
    WorkloadAttention wl;
    wl.seq_len = 256; wl.Br = 128; wl.Bc = 128; wl.d_head = 128;
    FA2Tiler::seed_hbm(wl, ts);

    // Q tiles  (2 tiles)
    CHECK(ts.has("HBM.Q[0:128,0:128]"));
    CHECK(ts.has("HBM.Q[128:256,0:128]"));

    // K tiles  (2 tiles)
    CHECK(ts.has("HBM.K[0:128,0:128]"));
    CHECK(ts.has("HBM.K[128:256,0:128]"));

    // V tiles  (2 tiles)
    CHECK(ts.has("HBM.V[0:128,0:128]"));
    CHECK(ts.has("HBM.V[128:256,0:128]"));

    // Output placeholders
    CHECK(ts.has("HBM.O[0:128,0:128]"));
    CHECK(ts.has("HBM.O[128:256,0:128]"));
    CHECK(ts.has("HBM.L[0:128]"));
    CHECK(ts.has("HBM.L[128:256]"));

    // Q tiles are seeded with non-trivial random data (not all zeros)
    const auto& q0 = ts.get("HBM.Q[0:128,0:128]");
    REQUIRE(q0.size() == 128u * 128u);
    bool has_nonzero = std::any_of(q0.begin(), q0.end(), [](float f){ return f != 0.f; });
    CHECK(has_nonzero);
}

// ===========================================================================
// 14. FA2 full-matrix YAML: metadata fields correct
// ===========================================================================

TEST_CASE("FA2 full-matrix YAML: metadata fields correct") {
    Schedule s = Schedule::from_yaml_file(FA2_FULL_SCH);

    CHECK(s.metadata.type   == "fa2_full_matrix");
    CHECK(s.metadata.Nq     == NQ_FULL);
    CHECK(s.metadata.Nkv    == NKV_FULL);
    CHECK(s.metadata.Br     == 128);
    CHECK(s.metadata.Bc     == 128);
    CHECK(s.metadata.d_head == 128);
    CHECK(s.metadata.is_fa2_full_matrix());
}

// ===========================================================================
// 15. FA2 full-matrix YAML: instruction count
// ===========================================================================

TEST_CASE("FA2 full-matrix YAML: instruction count is 15648") {
    Schedule s = Schedule::from_yaml_file(FA2_FULL_SCH);
    CHECK(s.instructions.size() == static_cast<size_t>(INSTRS_FULL));
}

// ===========================================================================
// 16. FA2Tiler small (2×2): all instructions complete
// ===========================================================================

TEST_CASE("FA2Tiler small (2x2) simulation: all instructions complete") {
    std::ostringstream ss;
    EventEngine engine;
    register_fa2_units(engine, ss);

    TensorStore ts;
    Schedule sched_obj;
    sched_obj.instructions = build_small(ts);
    REQUIRE(sched_obj.instructions.size() == static_cast<size_t>(INSTRS_SMALL));

    OpRegistry reg;
    add_all_delay_ops(reg);
    Scheduler sched(engine, reg, sched_obj);
    wire(engine, sched);

    sched.launch();
    engine.run();

    CHECK(sched.all_done());
    CHECK(sched.outstanding() == 0);
    CHECK(engine.current_cycle() > 0);
}

// ===========================================================================
// 17. FA2Tiler small (2×2): pipeline overlap
//     DMA for kv=1 starts before GEMM for kv=0 ends — verifies that the
//     DMA-prefetch/systolic-compute overlap is structurally correct.
// ===========================================================================

TEST_CASE("FA2Tiler small (2x2): DMA kv=1 starts before GEMM kv=0 finishes") {
    std::ostringstream ss;
    EventEngine engine;
    register_fa2_units(engine, ss);

    std::unordered_map<InstructionId, Cycle> start_at, done_at;
    engine.set_trace([&](const Event& e) {
        if (e.type == EventType::OP_START) start_at[e.instr] = e.cycle;
        if (e.type == EventType::OP_DONE)  done_at [e.instr] = e.cycle;
    });

    TensorStore ts;
    Schedule sched_obj;
    sched_obj.instructions = build_small(ts);

    OpRegistry reg;
    add_all_delay_ops(reg);
    Scheduler sched(engine, reg, sched_obj);
    wire(engine, sched);

    sched.launch();
    engine.run();

    // load_K[kv=1] is id = id_kv(1, OFF_LOAD_K) = 20
    // gemm_S[kv=0] is id = id_kv(0, OFF_GEMM_S) = 9
    InstructionId load_K_kv1 = static_cast<InstructionId>(id_kv(1, OFF_LOAD_K));
    InstructionId gemm_S_kv0 = static_cast<InstructionId>(id_kv(0, OFF_GEMM_S));

    REQUIRE(start_at.count(load_K_kv1) > 0);
    REQUIRE(done_at.count(gemm_S_kv0)  > 0);

    CHECK_MESSAGE(start_at[load_K_kv1] < done_at[gemm_S_kv0],
        "load_K[kv=1] (start=" << start_at[load_K_kv1]
        << ") should start before gemm_S[kv=0] finishes (done="
        << done_at[gemm_S_kv0] << ")");
}

// ===========================================================================
// 18. FA2Tiler small (2×2): Q-tile serialization
//     store_L[Q0] starts before Q1 prologue issues.
// ===========================================================================

TEST_CASE("FA2Tiler small (2x2): store_L[Q0] starts before Q1 prologue") {
    std::ostringstream ss;
    EventEngine engine;
    register_fa2_units(engine, ss);

    std::unordered_map<InstructionId, Cycle> start_at;
    engine.set_trace([&](const Event& e) {
        if (e.type == EventType::OP_START) start_at[e.instr] = e.cycle;
    });

    TensorStore ts;
    Schedule sched_obj;
    sched_obj.instructions = build_small(ts);

    OpRegistry reg;
    add_all_delay_ops(reg);
    Scheduler sched(engine, reg, sched_obj);
    wire(engine, sched);

    sched.launch();
    engine.run();

    static constexpr InstructionId STOR_L_Q0 =
        static_cast<InstructionId>(INSTRS_PER_Q_SMALL - 1);  // 38
    static constexpr InstructionId INIT_O_Q1 =
        static_cast<InstructionId>(INSTRS_PER_Q_SMALL);       // 39

    REQUIRE(start_at.count(STOR_L_Q0) > 0);
    REQUIRE(start_at.count(INIT_O_Q1) > 0);

    CHECK_MESSAGE(start_at[STOR_L_Q0] < start_at[INIT_O_Q1],
        "store_L[Q0] (start=" << start_at[STOR_L_Q0]
        << ") should precede Q1 prologue (start=" << start_at[INIT_O_Q1] << ")");
}

// ===========================================================================
// 19. FA2Tiler full (32×32): all instructions complete (delay-unit fast sim)
// ===========================================================================

TEST_CASE("FA2Tiler full (32x32) simulation: all 15648 instructions complete") {
    std::ostringstream ss;
    EventEngine engine;
    register_fa2_units(engine, ss);

    ArchConfig arch = ArchConfig::from_yaml_file(ARCH_PATH);
    TensorStore ts;
    WorkloadAttention wl = FA2Tiler::from_yaml_file(FA2_ATT_WL);
    auto instrs = FA2Tiler::decompose(wl, arch, ts);
    REQUIRE(instrs.size() == static_cast<size_t>(INSTRS_FULL));

    Schedule sched_obj;
    sched_obj.instructions = std::move(instrs);

    OpRegistry reg;
    add_all_delay_ops(reg);
    Scheduler sched(engine, reg, sched_obj);
    wire(engine, sched);

    sched.launch();
    engine.run();

    CHECK(sched.all_done());
    CHECK(sched.outstanding() == 0);
}

// ===========================================================================
// 20. FA2 full-matrix YAML schedule: all instructions complete (delay-unit sim)
// ===========================================================================

TEST_CASE("FA2 full-matrix YAML simulation: all 15648 instructions complete") {
    std::ostringstream ss;
    EventEngine engine;
    register_fa2_units(engine, ss);

    Schedule sched_obj = Schedule::from_yaml_file(FA2_FULL_SCH);
    REQUIRE(sched_obj.instructions.size() == static_cast<size_t>(INSTRS_FULL));

    OpRegistry reg;
    add_all_delay_ops(reg);
    Scheduler sched(engine, reg, sched_obj);
    wire(engine, sched);

    sched.launch();
    engine.run();

    CHECK(sched.all_done());
    CHECK(sched.outstanding() == 0);
}
