#include "core/event_engine.h"
#include "core/logger.h"
#include "core/tensor_store.h"
#include "config/arch_config.h"
#include "schedule/schedule.h"
#include "schedule/op_registry.h"
#include "schedule/scheduler.h"
#include "schedule/tiler.h"
#include "units/delay_unit.h"
#include "units/systolic_unit.h"
#include "units/dma_unit.h"
#include "units/buffer_unit.h"
#include "units/vector_unit.h"
#include "units/access_unit.h"
#include <iostream>
#include <string>
#include <stdexcept>
#include <unordered_map>

using namespace sim;

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------
static uint32_t dtype_bytes(const std::string& precision) {
    if (precision == "FP8")  return 1;
    if (precision == "FP32") return 4;
    return 2; // FP16 / BF16
}

// ---------------------------------------------------------------------------
// Op registration
// ---------------------------------------------------------------------------
static void register_all_ops(OpRegistry& reg, const ArchConfig& arch) {

    // delay — fixed latency on any unit pool (backward compat)
    reg.register_op("delay", [](const IssueCtx& ctx) {
        std::vector<UnitId> targets = ctx.engine.find_unit_pool(ctx.inst.unit);
        if (targets.empty())
            throw std::runtime_error("delay: unknown unit '" + ctx.inst.unit + "'");
        Cycle lat = static_cast<Cycle>(pget_int(ctx.inst.params, "latency_cycles", 10));
        UnitReservation res = ctx.scheduler.reserve_unit_pool(targets, lat);
        Event e;
        e.type=EventType::OP_START; e.target=res.id; e.cycle=res.start;
        e.instr=ctx.inst.id; e.label=ctx.inst.label;
        e.payload=static_cast<int64_t>(lat);
        ctx.engine.schedule(std::move(e));
    });

    // gemm — real systolic array with compute
    reg.register_op("gemm", [&arch](const IssueCtx& ctx) {
        UnitId t = ctx.engine.find_unit("systolic");
        if (t == INVALID_UNIT) throw std::runtime_error("gemm: systolic unit not found");
        GemmShape s;
        s.M     = (uint32_t)pget_int(ctx.inst.params, "M", arch.systolic.rows);
        s.K     = (uint32_t)pget_int(ctx.inst.params, "K", arch.systolic.rows);
        s.N     = (uint32_t)pget_int(ctx.inst.params, "N", arch.systolic.cols);
        s.src_a = pget_str(ctx.inst.params, "source_a");
        s.src_b = pget_str(ctx.inst.params, "source_b");
        s.dst_c = pget_str(ctx.inst.params, "destination");
        Event e; e.type=EventType::OP_START; e.target=t;
        e.cycle=ctx.engine.current_cycle(); e.instr=ctx.inst.id; e.label=ctx.inst.label;
        e.payload=s; ctx.engine.schedule(std::move(e));
    });

    // stage — IBUF → systolic_array.Q_operand  (on-chip, generated by Tiler)
    reg.register_op("stage", [&arch](const IssueCtx& ctx) {
        std::vector<UnitId> targets = ctx.engine.find_unit_pool(ctx.inst.unit);
        if (targets.empty()) throw std::runtime_error("stage: unknown unit");
        DmaTransfer xfer;
        xfer.bytes   = (uint64_t)pget_int(ctx.inst.params, "bytes", 0);
        xfer.on_chip = pget_bool(ctx.inst.params, "on_chip", true);
        xfer.src_buf = pget_str(ctx.inst.params, "src_buf");
        xfer.dst_buf = pget_str(ctx.inst.params, "dst_buf");
        UnitReservation res = ctx.scheduler.reserve_unit_pool(targets,
            static_cast<Cycle>(std::ceil(
                static_cast<double>(xfer.bytes) / arch.sram.banking_factor)));
        Event e; e.type=EventType::OP_START; e.target=res.id; e.cycle=res.start;
        e.instr=ctx.inst.id; e.label=ctx.inst.label;
        e.payload=xfer; ctx.engine.schedule(std::move(e));
    });

    // dma_load / dma_store — HBM ↔ IBUF
    auto dma_op = [&arch](const IssueCtx& ctx) {
        std::vector<UnitId> targets = ctx.engine.find_unit_pool(ctx.inst.unit);
        if (targets.empty()) throw std::runtime_error("dma: unknown unit");
        DmaTransfer xfer;
        xfer.bytes   = (uint64_t)pget_int(ctx.inst.params, "bytes", 0);
        xfer.on_chip = false;
        if (xfer.bytes == 0) {
            uint64_t r = (uint64_t)pget_int(ctx.inst.params, "rows", 0);
            uint64_t c = (uint64_t)pget_int(ctx.inst.params, "cols", 0);
            xfer.bytes = r * c * dtype_bytes(arch.systolic.precision);
        }
        xfer.src_buf = pget_str(ctx.inst.params, "src_buf");
        xfer.dst_buf = pget_str(ctx.inst.params, "dst_buf");
        // Use pool reservation so multiple DMA channels work correctly
        const double bw = arch.hbm_bytes_per_cycle() * arch.dma.channels;
        Cycle lat = static_cast<Cycle>(arch.hbm.latency_cycles) +
                    static_cast<Cycle>(std::ceil(xfer.bytes / bw));
        UnitReservation res = ctx.scheduler.reserve_unit_pool(targets, lat);
        Event e; e.type=EventType::OP_START; e.target=res.id; e.cycle=res.start;
        e.instr=ctx.inst.id; e.label=ctx.inst.label;
        e.payload=xfer; ctx.engine.schedule(std::move(e));
    };
    reg.register_op("dma_load",  dma_op);
    reg.register_op("dma_store", dma_op);

    // sram_read / sram_write
    auto sram_op = [&arch](bool is_write) {
        return [&arch, is_write](const IssueCtx& ctx) {
            UnitId t = ctx.engine.find_unit(
                is_write ? "shared_obuf" : "shared_ibuf");
            if (t == INVALID_UNIT) throw std::runtime_error("sram: unit not found");
            SramAccess a; a.is_write=is_write;
            a.bytes = (uint64_t)pget_int(ctx.inst.params, "bytes", 0);
            if (a.bytes == 0) {
                uint64_t r=(uint64_t)pget_int(ctx.inst.params,"rows",0);
                uint64_t c=(uint64_t)pget_int(ctx.inst.params,"cols",0);
                a.bytes = r*c*dtype_bytes(arch.systolic.precision);
            }
            Event e; e.type=EventType::OP_START; e.target=t;
            e.cycle=ctx.engine.current_cycle(); e.instr=ctx.inst.id; e.label=ctx.inst.label;
            e.payload=a; ctx.engine.schedule(std::move(e));
        };
    };
    reg.register_op("sram_read",  sram_op(false));
    reg.register_op("sram_write", sram_op(true));

    // Vector ops (scale, exp, softmax, layernorm, rope, rowmax, rowsum, etc.)
    struct VD { uint32_t passes; uint32_t exp_ops; };
    const std::unordered_map<std::string, VD> vec_defs = {
        {"scale",{1,0}},{"add",{1,0}},{"accumulate",{1,0}},{"normalize",{1,0}},
        {"rowmax",{1,0}},{"rowsum",{1,0}},{"exp",{1,1}},{"rope",{1,0}},
        {"softmax",{3,1}},{"layer_norm",{2,0}},{"logsumexp",{1,1}},
    };
    for (auto& [name, def] : vec_defs) {
        reg.register_op(name, [name, def](const IssueCtx& ctx) {
            std::vector<UnitId> targets = ctx.engine.find_unit_pool(ctx.inst.unit);
            if (targets.empty()) throw std::runtime_error(name + ": unknown unit");
            VectorOp op; op.kind=name;
            op.elements = (uint64_t)pget_int(ctx.inst.params,"elements",0);
            if (!op.elements) {
                uint64_t r=(uint64_t)pget_int(ctx.inst.params,"rows",0);
                uint64_t c=(uint64_t)pget_int(ctx.inst.params,"cols",0);
                uint64_t l=(uint64_t)pget_int(ctx.inst.params,"length",0);
                op.elements=(r&&c)?r*c:l;
            }
            op.passes  = (uint32_t)pget_int(ctx.inst.params,"passes",  def.passes);
            op.exp_ops = (uint32_t)pget_int(ctx.inst.params,"exp_ops", def.exp_ops);
            // Compute latency then reserve a unit from the pool
            // (latency computed from VectorUnit but we need it here for reservation)
            // Use a temporary to get the latency formula
            Event e; e.type=EventType::OP_START; e.instr=ctx.inst.id; e.label=ctx.inst.label;
            e.payload=op;
            // Just fire at the first available unit in the pool
            UnitReservation res = ctx.scheduler.reserve_unit_pool(targets, 1);
            e.target=res.id; e.cycle=res.start;
            ctx.engine.schedule(std::move(e));
        });
    }

    // Access-core ops
    for (auto* n : {"transpose","scatter","gather","init_fill"}) {
        std::string name = n;
        reg.register_op(name, [name](const IssueCtx& ctx) {
            std::vector<UnitId> targets = ctx.engine.find_unit_pool(ctx.inst.unit);
            if (targets.empty()) throw std::runtime_error(name+": unknown unit");
            AccessOp op; op.kind=name;
            op.elements=(uint64_t)pget_int(ctx.inst.params,"elements",0);
            if (!op.elements) {
                uint64_t r=(uint64_t)pget_int(ctx.inst.params,"rows",0);
                uint64_t c=(uint64_t)pget_int(ctx.inst.params,"cols",0);
                uint64_t l=(uint64_t)pget_int(ctx.inst.params,"length",0);
                op.elements=(r&&c)?r*c:l;
            }
            UnitReservation res = ctx.scheduler.reserve_unit_pool(targets, 1);
            Event e; e.type=EventType::OP_START; e.target=res.id; e.cycle=res.start;
            e.instr=ctx.inst.id; e.label=ctx.inst.label;
            e.payload=op; ctx.engine.schedule(std::move(e));
        });
    }
}

// ---------------------------------------------------------------------------
// Wire scheduler into every unit
// ---------------------------------------------------------------------------
static void wire_scheduler(EventEngine& engine, Scheduler& sched,
                            TensorStore& ts) {
    for (UnitId uid=0; uid<(UnitId)engine.num_units(); uid++) {
        Unit* u = engine.get_unit(uid);
        if (auto* x=dynamic_cast<DelayUnit*>   (u)){x->set_scheduler(&sched);continue;}
        if (auto* x=dynamic_cast<SystolicUnit*>(u)){x->set_scheduler(&sched);continue;}
        if (auto* x=dynamic_cast<DmaUnit*>     (u)){x->set_scheduler(&sched);x->set_tensor_store(&ts);continue;}
        if (auto* x=dynamic_cast<BufferUnit*>  (u)){x->set_scheduler(&sched);continue;}
        if (auto* x=dynamic_cast<VectorUnit*>  (u)){x->set_scheduler(&sched);continue;}
        if (auto* x=dynamic_cast<AccessUnit*>  (u)){x->set_scheduler(&sched);continue;}
    }
}

// ---------------------------------------------------------------------------
// main
// ---------------------------------------------------------------------------
int main(int argc, char** argv) {
    std::string config_path   = "configs/default.yaml";
    std::string sched_path    = "";
    std::string workload_path = "";
    bool        trace         = true;

    for (int i=1; i<argc; i++) {
        std::string a = argv[i];
        if      (a=="--config"   && i+1<argc) config_path   = argv[++i];
        else if (a=="--schedule" && i+1<argc) sched_path    = argv[++i];
        else if (a=="--workload" && i+1<argc) workload_path = argv[++i];
        else if (a=="--no-trace")             trace = false;
        else {
            std::cerr << "Usage: sim_main [--config FILE]"
                         " [--schedule FILE | --workload FILE] [--no-trace]\n";
            return 1;
        }
    }
    if (sched_path.empty() && workload_path.empty())
        sched_path = "schedules/dummy_example.yaml";

    ArchConfig arch = ArchConfig::from_yaml_file(config_path);

    std::cout << "clock=" << arch.clock_ghz << " GHz"
              << "  systolic=" << arch.systolic.rows << "x" << arch.systolic.cols
              << " " << (arch.systolic.bidirectional ? "bidir" : "unidir")
              << "  precision=" << arch.systolic.precision << "\n"
              << "hbm_bw=" << arch.hbm.bandwidth_tb_s << " TB/s"
              << "  hbm_bpc=" << arch.hbm_bytes_per_cycle() << " B/cyc"
              << "  hbm_lat=" << arch.hbm.latency_cycles << "\n"
              << "dma_ch=" << arch.dma.channels
              << "  ibuf=" << arch.sram.ibuf_kb << " KB"
              << "  obuf=" << arch.sram.obuf_kb << " KB"
              << "  bank=" << arch.sram.banking_factor << "\n\n";

    // ── TensorStore ──────────────────────────────────────────────────────
    TensorStore ts;
    Schedule    schedule;
    TileDecomposition tile_decomp;
    bool used_tiler = false;

    if (!workload_path.empty()) {
        WorkloadGemm wl = Tiler::from_yaml_file(workload_path);
        tile_decomp  = Tiler::decompose(wl, arch, ts);
        Tiler::print_decomposition(tile_decomp);
        schedule.instructions = tile_decomp.instructions;
        used_tiler = true;
    } else {
        schedule = Schedule::from_yaml_file(sched_path);
        // Pre-populate dummy buffers for hand-written schedules
        const uint32_t SA = arch.systolic.rows;
        ts.init_random("systolic_array.Q_operand", SA*SA, -1.f, 1.f, 1);
        ts.init_random("shared_ibuf.K_tile_T",     SA*SA, -1.f, 1.f, 2);
        ts.init_random("shared_ibuf.V_tile",       SA*SA, -1.f, 1.f, 3);
        ts.init_random("A", SA*SA, -1.f, 1.f, 5);
        ts.init_random("B", SA*SA, -1.f, 1.f, 6);
    }

    // ── Build engine ─────────────────────────────────────────────────────
    EventEngine engine(arch.clock_ghz);

    // Single units
    engine.register_unit(std::make_unique<SystolicUnit>("systolic",    arch.systolic, nullptr, &ts));
    engine.register_unit(std::make_unique<BufferUnit>  ("shared_ibuf", arch.sram));
    engine.register_unit(std::make_unique<BufferUnit>  ("shared_obuf", arch.sram));

    // Unit pools (named logical_name_0, logical_name_1, ...)
    for (uint32_t i=0; i<arch.dma.channels; i++)
        engine.register_unit(std::make_unique<DmaUnit>(
            "dma_" + std::to_string(i), arch, &ts));

    for (uint32_t i=0; i<arch.vector_cores; i++)
        engine.register_unit(std::make_unique<VectorUnit>(
            "vector_core_" + std::to_string(i), arch.vector_core));

    for (uint32_t i=0; i<arch.access_cores; i++)
        engine.register_unit(std::make_unique<AccessUnit>(
            "access_core_" + std::to_string(i), arch.access_core));

    // ── Register ops + scheduler ─────────────────────────────────────────
    OpRegistry reg;
    register_all_ops(reg, arch);

    Scheduler scheduler(engine, reg, schedule);
    wire_scheduler(engine, scheduler, ts);

    // ── Trace ─────────────────────────────────────────────────────────────
    ConsoleLogger logger(engine);
    if (trace) engine.set_trace([&](const Event& e){ logger(e); });

    // ── Run ───────────────────────────────────────────────────────────────
    std::cout << "== simulation start  instructions="
              << schedule.instructions.size() << " ==\n";
    scheduler.launch();
    Cycle final_cycle = engine.run();
    std::cout << "== simulation done"
              << "  cycle=" << final_cycle
              << "  (" << cycles_to_ns(final_cycle, arch.clock_ghz) << " ns)"
              << "  outstanding=" << scheduler.outstanding() << " ==\n";

    // ── Output ────────────────────────────────────────────────────────────
    if (used_tiler) {
        Tiler::assemble_output(tile_decomp, ts);
        const auto& wl = tile_decomp.workload;
        std::cout << "\nAssembled \"" << wl.dst_c << "\" ["
                  << wl.M << "×" << wl.N << "] from "
                  << tile_decomp.tiles.size() << " tiles:\n";
        ts.print(wl.dst_c, wl.M, wl.N, 4);
    } else {
        const uint32_t SA = arch.systolic.rows;
        for (const char* n : {"shared_obuf.S_tile","shared_obuf.S_sub_r0_c0","C"})
            if (ts.has(n)) ts.print(n, SA, SA, 4);
    }

    return scheduler.all_done() ? 0 : 1;
}
